### ISSUE TITLE
Sign in with Github not working?

### ISSUE THREAD

**Issue by coxandrew** [mendicant-original/community#2]
I clicked the "Sign in with Github" button, which took me to Github and asked me to "allow", which redirected me back to the site. The button was still there and there was no indication that I had been logged in successfully. When I click the button again, nothing happens.

**Comment by jordanbyron** [comment]
@coxandrew can you give it a try again? I think the user account creation was failing because you don't have a public email account, which it shouldn't

**Comment by coxandrew** [comment]
Yep - it's working now. Thanks!
