### ISSUE TITLE
Activities can have a deadline

### ISSUE THREAD

**Issue by jordanbyron** [mendicant-original/community#21]
When a deadline is set, the activity will appear towards the top of the list and be sorted by deadline. Kinda link a sticky post, but with dates involved.

The deadline should also be shown on the activity with a litte clock icon.

**Comment by madebydna** [comment]
This sounds pretty straightforward, so I'll give it a shot. 

I guess a deadline is not supposed to represent an end date (because that would apply to almost _all_ activities), but rather a date by which a certain action needs to be taken, like for example a registration deadline. 

Some UI questions: Should we use a calendar date picker for setting the deadline? Regarding the clock icon, what kind did you have in mind, how big, etc.?

**Comment by jordanbyron** [comment]
> I guess a deadline is not supposed to represent an end date (because that would apply to almost all activities), but rather a date by which a certain action needs to be taken, like for example a registration deadline.

Kind of. Think of deadlines as dynamic, "need to be in front of our members" criteria. The closer we get to a deadline, we want that activity to be closer to the top. If an activity has a deadline and it's tomorrow, then we don't want it buried by 20 other posts which aren't due for another month.

> Should we use a calendar date picker for setting the deadline?

I generally hate those things. Go for the simple version first: `date_select` I think it is. Remember we're trying to go simple.

> Regarding the clock icon, what kind did you have in mind, how big, etc.?

This one should do the trick:

[![clock](http://i.imgur.com/7bqQF.png)](http://i.imgur.com/7bqQF.png)

You might have to size it a bit to fit next to the text. The deadline should be nice and humanized: `January 4, 2011` and be displayed in the sidebar with the author's name and number of participants.

@sandal anything here I am missing?

Thanks for working on this Andrea :smile:

**Comment by practicingruby** [comment]
@jordanbyron, @madebydna : I hate `date_select` though, I can never remember how the days of the week match with the dates and so calendar widgets help me with that. Could we use the calendar widget that Momentum uses?

**Comment by jordanbyron** [comment]
@sandal we certainly could use jQuery UI. The only reason I suggested we go the simple `date_select` route is it doesn't require we pull in another javascript framework and set of stylesheets. Of course it's fairly easy to do, but we'd need to pick a suitable style for the calendar picker so it doesn't look tacked on.

@madebydna I think you can create a design on jQuery UI's site and then share it with us. Why don't you start there?

**Comment by practicingruby** [comment]
I'm more concerned about not adding new major areas of functionality, rather than avoiding executing existing planned features well, so I don't mind the dependency.

**Comment by madebydna** [comment]
@sandal, @jordanbyron: jQuery UI sounds like a good compromise between adding on third-party dependencies and making the UI easy to use.

> I think you can create a design on jQuery UI's site and then share it with us. Why don't you start there?

I guess you mean this: [jQuery UI - themeroller](http://jqueryui.com/themeroller/). It lets you create and download your own theme. The only problem is that the generated CSS will include all kinds of styles that are no specific to the date picker widget. 

So the question is shall I simply extract the relevant parts from the generated theme, or else settle on a theme, install it in its entirety so we can use it for other jQuery UI widgets in the future.

**Comment by jordanbyron** [comment]
> So the question is shall I simply extract the relevant parts from the generated theme, or else settle on a theme, install it in its entirety so we can use it for other jQuery UI widgets in the future.

Pull in the entire theme. That way in the future if we decide to use more jquery widgets they will be simple to add.

**Comment by madebydna** [comment]
OK. Will do. And I'll let you check out the theme beforehand.

I probably won't be able to get started on this today, but I'll work on it tomorrow.

**Comment by madebydna** [comment]
@jordanbyron, what do you think of this jQuery UI theme for the community site:

[Altered Smoothness](http://jqueryui.com/themeroller/#ffDefault=Helvetica%2C+Arial%2Csans-serif&fwDefault=normal&fsDefault=1.1em&cornerRadius=3px&bgColorHeader=ececec&bgTextureHeader=03_highlight_soft.png&bgImgOpacityHeader=75&borderColorHeader=aaaaaa&fcHeader=43465e&iconColorHeader=43465e&bgColorContent=ffffff&bgTextureContent=01_flat.png&bgImgOpacityContent=75&borderColorContent=aaaaaa&fcContent=222222&iconColorContent=222222&bgColorDefault=e6e6e6&bgTextureDefault=02_glass.png&bgImgOpacityDefault=75&borderColorDefault=d3d3d3&fcDefault=555555&iconColorDefault=888888&bgColorHover=dadada&bgTextureHover=02_glass.png&bgImgOpacityHover=75&borderColorHover=999999&fcHover=212121&iconColorHover=454545&bgColorActive=ffffff&bgTextureActive=02_glass.png&bgImgOpacityActive=65&borderColorActive=aaaaaa&fcActive=212121&iconColorActive=454545&bgColorHighlight=fbf9ee&bgTextureHighlight=02_glass.png&bgImgOpacityHighlight=55&borderColorHighlight=fcefa1&fcHighlight=363636&iconColorHighlight=2e83ff&bgColorError=fef1ec&bgTextureError=02_glass.png&bgImgOpacityError=95&borderColorError=cd0a0a&fcError=cd0a0a&iconColorError=cd0a0a&bgColorOverlay=aaaaaa&bgTextureOverlay=01_flat.png&bgImgOpacityOverlay=0&opacityOverlay=30&bgColorShadow=aaaaaa&bgTextureShadow=01_flat.png&bgImgOpacityShadow=0&opacityShadow=30&thicknessShadow=8px&offsetTopShadow=-8px&offsetLeftShadow=-8px&cornerRadiusShadow=8px)

I based it on the Smoothness theme and changed a few things, like the font to Helvetica, made the edges a little less round and re-introduced the header color in some places.

Let me know if you think we can go with it or if you want to make any other changes.

**Comment by madebydna** [comment]
@jordanbyron, another question about the ordering logic of activities with or without deadlines: 

I'm assuming that we'll first list all activities that _have_ a deadline showing the activity with the earliest deadline first. Then come the other activities in the order they were created. Is that what you had in mind?

**Comment by jordanbyron** [comment]
> What do you think of this jQuery UI theme for the community site

That looks good to me. I might want to make some tweaks once I see it in the site, but this is a solid start.

> I'm assuming that we'll first list all activities that have a deadline showing the activity with the earliest deadline first. Then come the other activities in the order they were created. Is that what you had in mind?

That is correct. Thanks for working on this :smile:
:fire_engine:
