### ISSUE TITLE
Feature Idea: Unread count in navigation

### ISSUE THREAD

**Issue by jordanbyron** [mendicant-original/community#26]
![mockup](http://i.imgur.com/cARsM.png)

Right now it's difficult to know if content has been added to different sections of the site without browsing each area every visit. These badges would indicate how many new [articles | activities] were posted since the user's last visit.

**Comment by samnang** [comment]
Should the number in each badges are calculated from `total [articles | activities ] - visited [articles | activities ]`? So we have to keep track every user browsing [article | activity] show page to mark it has been visited by the user. But currently, most of the time I don't go to article show page because there is no any different from viewing in articles index page.

What I come up in mind for implementation create two models visited_article(user_id, article_id), visited_activity(user_id, activity_id). What do you think?

**Comment by seejee** [comment]
Maybe it could be even simpler. If we are ok with having less granularity, it could be as simple as:

```
SELECT COUNT() of [articles | activities] WHERE create_date > User.last_login_date
```

**Comment by jordanbyron** [comment]
> Should the number in each badges are calculated from total [articles | activities ] - visited [articles | activities ] ? So we have to keep track every user browsing [article | activity] show page to mark it has been visited by the user. 

That sounds right to me. 

> But currently, most of the time I don't go to article show page because there is no any different from viewing in articles index page.

When drawing up this idea I thought the same thing. I'm not sure the best approach to solving this problem. Any ideas?

> What I come up in mind for implementation create two models visited_article(user_id, article_id), visited_activity(user_id, activity_id). 

Rather than creating two new models, why not just create one generic model and use [polymorphic associations](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations) to join it to `Article` and `Activity`. Then if we add another section, it's very simple to add view counting to that model as well.

**Comment by jordanbyron** [comment]
@geihsler I'm not sure if that would work, because I'd assume we'd update `User#last_login_date` the moment they hit any page. Because I rarely "sign out" of community, that number would just get bigger and bigger if we only updated it when the user is authenticated with GitHub.

Additionally, if we did that, the `last_login_date` would be set to `Date.today` and those numbers would never be visible. However I really like the simple, out of the box approach. I wonder if there is something similar that would work?

**Comment by seejee** [comment]
@jordanbyron I think you're right. I like trying to keep things simple, but after thinking more about it, I can't think of a way around having a model that keeps track of who has read each article.

**Comment by steveklabnik** [comment]
This sounds like a job for Redis! http://blog.getspool.com/2011/11/29/fast-easy-realtime-metrics-using-redis-bitmaps/

**Comment by jordanbyron** [comment]
:scream: Redis might be the best tool for the job, but when I weigh out the pros vs the cons for a project of this size and scale, I don't think adding a Redis dependency makes the most sense. Ideally I want to keep community as easy to contribute to as possible. Setting up Redis is another hurdle would-be contributors need to overcome.

Of course I'm open to changing my mind :wink:

**Comment by steveklabnik** [comment]
Hahaha. No, I agree, we shouldn't need to introduce anything crazy. It _is_ an awesome technique for this kind of thing, though.

**Comment by samnang** [comment]
I agree, let's start with simple implementation first before dealing with optimization.

> Rather than creating two new models, why not just create one generic model and use polymorphic associations to join it to Article and Activity. Then if we add another section, it's very simple to add view counting to that model as well.

That's a good idea.

> > But currently, most of the time I don't go to article show page because there is no any different from viewing in articles index page.
> 
> When drawing up this idea I thought the same thing. I'm not sure the best approach to solving this problem. Any ideas?

If we have implemented commenting system on show page, that would be make sense for users go to show page. And another idea is to implement each article could be focus when users scroll down like good reader does, but it will involve some javascript to send ajax to mark as read/visit when the article get focus.

First let me get started with a simple implementation to mark as read/visited on user show page.

**Comment by samnang** [comment]
@jordanbyron let help me to get it style :smile:

**Comment by jordanbyron** [comment]
@samnang fantastic! First thing I should let you know, I've decided to flip the numbers and put them before the section link. I think that flows a bit better than my original design. For example:

**2 Updates** sounds much better to me that **Updates 2**. That change is already reflected in the unread_count branch. 

As for styling, all of this code should be put in the `_navigation.sass` partial. The spans you created are a great place to start. Luckily, I've already created a similar style for our flash messages. See if you can use the styling of `.flash` in `_flash.sass` as a starting place. Ignore any `position` attributes for now. We'll tackle those last.

Also don't forget to send over another pull request once you've got some code ready for me to look at. :computer:

**Comment by samnang** [comment]
Finished adding style and include in this pull request https://github.com/mendicant-university/community/pull/70
