### ISSUE TITLE
Long user names break profile pages

### ISSUE THREAD

**Issue by jordanbyron** [mendicant-original/community#37]
I've once again failed the "Nerian" test:

http://community.mendicantuniversity.org/people/Nerian

**Comment by Nerian** [comment]
Maybe resize the font according to its length?

``` js
var name_size = $('.name').html().length
if (name_size > 26)
  $('.name').css('font-size', 48 - (name_size/2) + 'px')
```

That code renders my name well.

**Comment by gjp** [comment]
Tricky:

MMMMMMMMMM
vs.
iiiiiiiiii

I guess you'd need to query the (fixed) width of the surrounding element, then iteratively shrink and re-render the text within a second element until the second element is smaller than the first.

This feels like something that ought to be a jQuery plugin already. (working...working...)

maybe https://github.com/davatron5000/FitText.js ?
demo @ http://fittextjs.com/

**Comment by jordanbyron** [comment]
@gjp I've see Fit Text before. That might just be what the doctor ordered. Nice find :smile:

**Comment by gjp** [comment]
Jordan, I'd like to have a go at this one. Based on the size of FitText, this can probably be done in a few lines of jQuery with or without a plugin.

**Comment by jordanbyron** [comment]
@gjp it's all yours :smile:

**Comment by gjp** [comment]
FitText won't work here. [BigText](https://github.com/zachleat/BigText) looks like it will. The maximum font size must be specified via Javascript, which puts styling responsibility in the wrong place. I'm going to fiddle with this to see if I can improve on that.

**Comment by jordanbyron** [comment]
@Nerian looks like you can update your [community profile](http://community.mendicantuniversity.org/people/Nerian) and stop shaming my bad design :wink2: :heart:

**Comment by Nerian** [comment]
Sweeeet :)  Good job!  :clap:
