### ISSUE TITLE
Front Page Stories should be clipped

### ISSUE THREAD

**Issue by semmons99** [mendicant-original/community#39]
Stories are starting to get too long for the front page. We need to clip them and provide a link that either goes to the full story, or reveals the full story in place.

**Comment by practicingruby** [comment]
We've had a few long ones, I agree. But I think this can be solved with a simple message on the update page "If your update is on the longer side, please consider posting it elsewhere and linking to it via an abstract here, unless you REALLY want to share the whole thing with the community".

Cultural Guidelines > Extra Features.

**Comment by practicingruby** [comment]
I looked through the 26 posts and I'd say three of them are longer than we'd like to see on this site. Two of those were from me though. That to me tells me we _really_ don't need this.

**Comment by practicingruby** [comment]
I fixed the website. No post is now more than a few paragraphs of content.

Here's a policy to remember: Don't create a policy/set of features to prevent a couple edge cases from causing problems if a small workaround will do.
