### ISSUE TITLE
I can't log in using github

### ISSUE THREAD

**Issue by Nerian** [mendicant-original/community#4]
I can't log in using github. I get a `your github account is not registered in University web`

**Comment by jordanbyron** [comment]
@Nerian give it another try. Looks like the User API in University-Web was case sensitive.

**Comment by Nerian** [comment]
Something went wrong :)

**Comment by jordanbyron** [comment]
@Nerian ok one problem fixed, another cropped up. Try it one more time. Looks like the gravatar code I wrote gets upset if your email address is blank

**Comment by Nerian** [comment]
Working like a charm, thank you!
