### ISSUE TITLE
Use Name / Email from University Web when creating accounts

### ISSUE THREAD

**Issue by jordanbyron** [mendicant-original/community#6]

**Comment by ericgj** [comment]
Might be able to work on this one - assuming it's still needed? 

So I understand correctly, it should pull in name / email when it checks permissions on university-web, instead of using name / email from Github (omniauth hash) ?

**Comment by jordanbyron** [comment]
Sure is still needed.

Right now `User.create_from_hash` uses Github's information, which is not always as complete or accurate as the information we have in university-web. So we want to pass the user's name and email from university-web (via the returned information in the service call) into `User.create_from_hash`

I don't remember if name and email are returned from the service call to university-web. If they aren't, then we'll need to do that first. Thanks for working on this Eric :smile:
