### ISSUE TITLE
Sign In/Out should return you to the same location

### ISSUE THREAD

**Issue by semmons99** [mendicant-original/community#78]
Currently if you're reading an update and Sign In/Out, you are redirect back to the index. This is slightly jarring. Better to return the user to their previous page.

**Comment by samnang** [comment]
I see Omniauth provides us a way[0] to save user location before sending to authenticate. And we might also could remove some codes in ApplicationController like `store_location` if the way Omniauth could handle it for us already. If you don't mind, I could start to work on this.

[0] https://github.com/intridea/omniauth/wiki/Saving-User-Location

**Comment by jordanbyron** [comment]
@samnang great find! I've assigned this ticket to you. Make sure we replace any occurrence of `redirect_back_or_default` and `store_location` when you make this change.
